attack_metadata:
  attack_name: "Lidar Attack: Object Side Patch"
  description: "The attack adds lidar patches in the form of a square at specific points around a front target vehicle, aiming to hide the vehicle from the perception stack of the ego vehicle."

attack_run_info: #For running attack!
  enabled: true
  attack_type: lidar_object_patch #This must match what is specified in attack manager!
  attack_class: Hiding Attack

# Patches should be computed in a pre-analysis!
patches: #Put all patches here - the front car is estimated as a 2d bounding box: x,y,z offsets are computed relative to that
  - x_offset: 0.43 #positive: behind car, negative in front of car
    y_offset: 0.91 # positive: next to the car, negative: overlapping with car (only makes sense if patch is in front or above car!)
    z_offset: 1.58 # always positive
    patch_size: 0.4 #patch is a square
    side: left #Side where patches are applied
    stabilize_anchor: false #This anchors the patch when the attack is first applied, i.e. the location of the patch is not recomputed

  - x_offset: 1.45
    y_offset: -0.51
    z_offset: 1.73
    patch_size: 0.4
    side: right
    stabilize_anchor: false

  - x_offset: -0.31
    y_offset: 0.64
    z_offset: 0.26
    patch_size: 0.4
    side: right
    stabilize_anchor: false

  - x_offset: -0.23
    y_offset: -0.11
    z_offset: 0.74
    patch_size: 0.4
    side: left
    stabilize_anchor: false

  - x_offset: 2.4
    y_offset: 0.49
    z_offset: 2.2
    patch_size: 0.4
    side: left
    stabilize_anchor: false

#In which region the attack should be applied
front_filter: #Only apply attack to vehicles at the front
  x_min: 3.0
  x_max: 40.0
  y_abs_max: 4.0
  z_min: -1.9 #At -2 - -2.1 there are ground points
  z_max: 2.0


    